export const PERSON_QUERY_BASE = 'PERSON_QUERY_BASE';

export const ORDER_UNPAY = 'ORDER_UNPAY';     /*未支付的订单*/
export const ORDER_PAY = 'ORDER_PAY'; /*已支付的订单*/
//获取类别
export const CLASSIFY_QUERY_GOODS = "CLASSIFY_QUERY_GOODS";
export const CLASSIFY_QUERY_CATEGORY = "CLASSIFY_QUERY_CATEGORY";
/*轮播图的index*/
export const PRODUCT_DETAIL_STEPINDEX = 'PRODUCT_DETAIL_STEPINDEX';
/*获取评价列表信息*/
export const PRODUCT_DETAIL_COMMENTLIST = 'PRODUCT_DETAIL_COMMENTLIST';

/*首页*/
export const PRODUCT_BRANDFLOOR='PRODUCT_BRANDFLOOR';

/* 获取产品列表 */
export const QUERY_GOODS_LIST = 'QUERY_GOODS_LIST';

//购物车
export const SHOP_CART_INFO = "SHOP_CART_INFO";
export const ADD_SHOP_CART = "ADD_SHOP_CART";
export const SHOP_CART_REMOVE = "SHOP_CART_REMOVE";
export const SHOP_CART_INPUTNUM = "SHOP_CART_INPUTNUM";
export const SHOP_CART_CHANGENUM = "SHOP_CART_CHANGENUM";
export const SHOP_CART_CHANGECHECK = "SHOP_CART_CHANGECHECK";
export const SHOP_CART_TOTALNUM = "SHOP_CART_TOTALNUM";
export const SHOP_CART_SELECTEALL = "SHOP_CART_SELECTALL";
export const SHOP_CART_REMOVEARY = "SHOP_CART_REMOVEARY";

// 商品规格
export const SET_PRODUCT_COMMERCIAL = "SET_PRODUCT_COMMERCIAL";

//支付
export const PAY_GOODS='PAY_GOODS';

//获取订单详情
export const PRODUCT_DETAIL_CONFIRM='PRODUCT_DETAIL_CONFIRM';
